import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"],weight: ["400",'800','700'] });

export const metadata: Metadata = {
  title: "Magic Post",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        ></meta>
      </head>
      <body className={inter.className}>
        {children}
        <Toaster richColors theme="light" />
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";
